// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// unc_caviar_indgarch
arma::vec unc_caviar_indgarch(arma::rowvec coefficients, arma::uword p, arma::uword q, arma::uword maximum, arma::mat lagged_y, double emp_quantil, arma::vec VaR_vector, arma::uword time);
RcppExport SEXP _QuantileModels_unc_caviar_indgarch(SEXP coefficientsSEXP, SEXP pSEXP, SEXP qSEXP, SEXP maximumSEXP, SEXP lagged_ySEXP, SEXP emp_quantilSEXP, SEXP VaR_vectorSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type coefficients(coefficientsSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type p(pSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type q(qSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type maximum(maximumSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lagged_y(lagged_ySEXP);
    Rcpp::traits::input_parameter< double >::type emp_quantil(emp_quantilSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type VaR_vector(VaR_vectorSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(unc_caviar_indgarch(coefficients, p, q, maximum, lagged_y, emp_quantil, VaR_vector, time));
    return rcpp_result_gen;
END_RCPP
}
// OBJF_unc_caviar_INDGARCH
double OBJF_unc_caviar_INDGARCH(arma::rowvec coefficients, const arma::vec& yes, double tau, arma::uword p, arma::uword q, arma::uword maximum, arma::mat lagged_y, double emp_quantil, arma::vec residuos, arma::vec VaR_vector, arma::uword time);
RcppExport SEXP _QuantileModels_OBJF_unc_caviar_INDGARCH(SEXP coefficientsSEXP, SEXP yesSEXP, SEXP tauSEXP, SEXP pSEXP, SEXP qSEXP, SEXP maximumSEXP, SEXP lagged_ySEXP, SEXP emp_quantilSEXP, SEXP residuosSEXP, SEXP VaR_vectorSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type coefficients(coefficientsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type yes(yesSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type p(pSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type q(qSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type maximum(maximumSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lagged_y(lagged_ySEXP);
    Rcpp::traits::input_parameter< double >::type emp_quantil(emp_quantilSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type residuos(residuosSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type VaR_vector(VaR_vectorSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(OBJF_unc_caviar_INDGARCH(coefficients, yes, tau, p, q, maximum, lagged_y, emp_quantil, residuos, VaR_vector, time));
    return rcpp_result_gen;
END_RCPP
}
// unc_caviar_sav
arma::vec unc_caviar_sav(arma::rowvec coefficients, arma::uword p, arma::uword q, arma::uword maximum, arma::mat lagged_y, double emp_quantil, arma::vec VaR_vector, arma::uword time);
RcppExport SEXP _QuantileModels_unc_caviar_sav(SEXP coefficientsSEXP, SEXP pSEXP, SEXP qSEXP, SEXP maximumSEXP, SEXP lagged_ySEXP, SEXP emp_quantilSEXP, SEXP VaR_vectorSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type coefficients(coefficientsSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type p(pSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type q(qSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type maximum(maximumSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lagged_y(lagged_ySEXP);
    Rcpp::traits::input_parameter< double >::type emp_quantil(emp_quantilSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type VaR_vector(VaR_vectorSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(unc_caviar_sav(coefficients, p, q, maximum, lagged_y, emp_quantil, VaR_vector, time));
    return rcpp_result_gen;
END_RCPP
}
// OBJF_unc_caviar_SAV
double OBJF_unc_caviar_SAV(arma::rowvec coefficients, const arma::vec& yes, double tau, arma::uword p, arma::uword q, arma::uword maximum, arma::mat lagged_y, double emp_quantil, arma::vec residuos, arma::vec VaR_vector, arma::uword time);
RcppExport SEXP _QuantileModels_OBJF_unc_caviar_SAV(SEXP coefficientsSEXP, SEXP yesSEXP, SEXP tauSEXP, SEXP pSEXP, SEXP qSEXP, SEXP maximumSEXP, SEXP lagged_ySEXP, SEXP emp_quantilSEXP, SEXP residuosSEXP, SEXP VaR_vectorSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type coefficients(coefficientsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type yes(yesSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type p(pSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type q(qSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type maximum(maximumSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lagged_y(lagged_ySEXP);
    Rcpp::traits::input_parameter< double >::type emp_quantil(emp_quantilSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type residuos(residuosSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type VaR_vector(VaR_vectorSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(OBJF_unc_caviar_SAV(coefficients, yes, tau, p, q, maximum, lagged_y, emp_quantil, residuos, VaR_vector, time));
    return rcpp_result_gen;
END_RCPP
}
// unc_caviar_as
arma::vec unc_caviar_as(arma::rowvec coefficients, arma::uword p, arma::uword q, arma::uword maximum, arma::mat lagged_y, double emp_quantil, arma::vec VaR_vector, arma::uword time);
RcppExport SEXP _QuantileModels_unc_caviar_as(SEXP coefficientsSEXP, SEXP pSEXP, SEXP qSEXP, SEXP maximumSEXP, SEXP lagged_ySEXP, SEXP emp_quantilSEXP, SEXP VaR_vectorSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type coefficients(coefficientsSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type p(pSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type q(qSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type maximum(maximumSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lagged_y(lagged_ySEXP);
    Rcpp::traits::input_parameter< double >::type emp_quantil(emp_quantilSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type VaR_vector(VaR_vectorSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(unc_caviar_as(coefficients, p, q, maximum, lagged_y, emp_quantil, VaR_vector, time));
    return rcpp_result_gen;
END_RCPP
}
// OBJF_unc_caviar_AS
double OBJF_unc_caviar_AS(arma::rowvec coefficients, const arma::vec& yes, double tau, arma::uword p, arma::uword q, arma::uword maximum, arma::mat lagged_y, double emp_quantil, arma::vec residuos, arma::vec VaR_vector, arma::uword time);
RcppExport SEXP _QuantileModels_OBJF_unc_caviar_AS(SEXP coefficientsSEXP, SEXP yesSEXP, SEXP tauSEXP, SEXP pSEXP, SEXP qSEXP, SEXP maximumSEXP, SEXP lagged_ySEXP, SEXP emp_quantilSEXP, SEXP residuosSEXP, SEXP VaR_vectorSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type coefficients(coefficientsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type yes(yesSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type p(pSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type q(qSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type maximum(maximumSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lagged_y(lagged_ySEXP);
    Rcpp::traits::input_parameter< double >::type emp_quantil(emp_quantilSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type residuos(residuosSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type VaR_vector(VaR_vectorSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(OBJF_unc_caviar_AS(coefficients, yes, tau, p, q, maximum, lagged_y, emp_quantil, residuos, VaR_vector, time));
    return rcpp_result_gen;
END_RCPP
}
// unc_caviar_i_caviar
arma::vec unc_caviar_i_caviar(arma::rowvec coefficients, arma::vec lagged_abs_y, double emp_quantil, arma::vec positive, arma::vec VaR_vector, arma::uword time);
RcppExport SEXP _QuantileModels_unc_caviar_i_caviar(SEXP coefficientsSEXP, SEXP lagged_abs_ySEXP, SEXP emp_quantilSEXP, SEXP positiveSEXP, SEXP VaR_vectorSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type coefficients(coefficientsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lagged_abs_y(lagged_abs_ySEXP);
    Rcpp::traits::input_parameter< double >::type emp_quantil(emp_quantilSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type positive(positiveSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type VaR_vector(VaR_vectorSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(unc_caviar_i_caviar(coefficients, lagged_abs_y, emp_quantil, positive, VaR_vector, time));
    return rcpp_result_gen;
END_RCPP
}
// OBJF_cons_caviar_ICAV
double OBJF_cons_caviar_ICAV(arma::rowvec coefficients, const arma::vec& yes, double tau, arma::vec positive, arma::mat lagged_y, double emp_quantil, arma::vec residuos, arma::vec VaR_vector, arma::uword time);
RcppExport SEXP _QuantileModels_OBJF_cons_caviar_ICAV(SEXP coefficientsSEXP, SEXP yesSEXP, SEXP tauSEXP, SEXP positiveSEXP, SEXP lagged_ySEXP, SEXP emp_quantilSEXP, SEXP residuosSEXP, SEXP VaR_vectorSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type coefficients(coefficientsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type yes(yesSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type positive(positiveSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lagged_y(lagged_ySEXP);
    Rcpp::traits::input_parameter< double >::type emp_quantil(emp_quantilSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type residuos(residuosSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type VaR_vector(VaR_vectorSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(OBJF_cons_caviar_ICAV(coefficients, yes, tau, positive, lagged_y, emp_quantil, residuos, VaR_vector, time));
    return rcpp_result_gen;
END_RCPP
}
// MVMQ_FILTER
arma::mat MVMQ_FILTER(arma::rowvec coefficients, arma::mat lagged_abs_y, arma::uword N, arma::uword p, arma::uword q, arma::mat VaR_vector, arma::uword time, arma::uword maximum);
RcppExport SEXP _QuantileModels_MVMQ_FILTER(SEXP coefficientsSEXP, SEXP lagged_abs_ySEXP, SEXP NSEXP, SEXP pSEXP, SEXP qSEXP, SEXP VaR_vectorSEXP, SEXP timeSEXP, SEXP maximumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type coefficients(coefficientsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lagged_abs_y(lagged_abs_ySEXP);
    Rcpp::traits::input_parameter< arma::uword >::type N(NSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type p(pSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type q(qSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type VaR_vector(VaR_vectorSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type time(timeSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type maximum(maximumSEXP);
    rcpp_result_gen = Rcpp::wrap(MVMQ_FILTER(coefficients, lagged_abs_y, N, p, q, VaR_vector, time, maximum));
    return rcpp_result_gen;
END_RCPP
}
// SAV_FILTER_for_jaco
arma::vec SAV_FILTER_for_jaco(arma::rowvec coefficients, arma::uword serie, arma::mat lagged_abs_y, arma::uword N, arma::uword p, arma::uword q, arma::mat VaR_vector, arma::uword time, arma::uword maximum);
RcppExport SEXP _QuantileModels_SAV_FILTER_for_jaco(SEXP coefficientsSEXP, SEXP serieSEXP, SEXP lagged_abs_ySEXP, SEXP NSEXP, SEXP pSEXP, SEXP qSEXP, SEXP VaR_vectorSEXP, SEXP timeSEXP, SEXP maximumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type coefficients(coefficientsSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type serie(serieSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lagged_abs_y(lagged_abs_ySEXP);
    Rcpp::traits::input_parameter< arma::uword >::type N(NSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type p(pSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type q(qSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type VaR_vector(VaR_vectorSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type time(timeSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type maximum(maximumSEXP);
    rcpp_result_gen = Rcpp::wrap(SAV_FILTER_for_jaco(coefficients, serie, lagged_abs_y, N, p, q, VaR_vector, time, maximum));
    return rcpp_result_gen;
END_RCPP
}
// OBJ_F_MVMQ
double OBJ_F_MVMQ(arma::rowvec coefficients, arma::mat lagged_abs_y, arma::uword N, arma::uword p, arma::uword q, arma::mat VaR_vector, arma::uword time, arma::uword maximum, arma::vec tau, arma::mat residuos, arma::mat series);
RcppExport SEXP _QuantileModels_OBJ_F_MVMQ(SEXP coefficientsSEXP, SEXP lagged_abs_ySEXP, SEXP NSEXP, SEXP pSEXP, SEXP qSEXP, SEXP VaR_vectorSEXP, SEXP timeSEXP, SEXP maximumSEXP, SEXP tauSEXP, SEXP residuosSEXP, SEXP seriesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type coefficients(coefficientsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lagged_abs_y(lagged_abs_ySEXP);
    Rcpp::traits::input_parameter< arma::uword >::type N(NSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type p(pSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type q(qSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type VaR_vector(VaR_vectorSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type time(timeSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type maximum(maximumSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type residuos(residuosSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type series(seriesSEXP);
    rcpp_result_gen = Rcpp::wrap(OBJ_F_MVMQ(coefficients, lagged_abs_y, N, p, q, VaR_vector, time, maximum, tau, residuos, series));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_QuantileModels_unc_caviar_indgarch", (DL_FUNC) &_QuantileModels_unc_caviar_indgarch, 8},
    {"_QuantileModels_OBJF_unc_caviar_INDGARCH", (DL_FUNC) &_QuantileModels_OBJF_unc_caviar_INDGARCH, 11},
    {"_QuantileModels_unc_caviar_sav", (DL_FUNC) &_QuantileModels_unc_caviar_sav, 8},
    {"_QuantileModels_OBJF_unc_caviar_SAV", (DL_FUNC) &_QuantileModels_OBJF_unc_caviar_SAV, 11},
    {"_QuantileModels_unc_caviar_as", (DL_FUNC) &_QuantileModels_unc_caviar_as, 8},
    {"_QuantileModels_OBJF_unc_caviar_AS", (DL_FUNC) &_QuantileModels_OBJF_unc_caviar_AS, 11},
    {"_QuantileModels_unc_caviar_i_caviar", (DL_FUNC) &_QuantileModels_unc_caviar_i_caviar, 6},
    {"_QuantileModels_OBJF_cons_caviar_ICAV", (DL_FUNC) &_QuantileModels_OBJF_cons_caviar_ICAV, 9},
    {"_QuantileModels_MVMQ_FILTER", (DL_FUNC) &_QuantileModels_MVMQ_FILTER, 8},
    {"_QuantileModels_SAV_FILTER_for_jaco", (DL_FUNC) &_QuantileModels_SAV_FILTER_for_jaco, 9},
    {"_QuantileModels_OBJ_F_MVMQ", (DL_FUNC) &_QuantileModels_OBJ_F_MVMQ, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_QuantileModels(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
