# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

unc_caviar_indgarch <- function(coefficients, p, q, maximum, lagged_y, emp_quantil, VaR_vector, time) {
    .Call(`_QuantileModels_unc_caviar_indgarch`, coefficients, p, q, maximum, lagged_y, emp_quantil, VaR_vector, time)
}

OBJF_unc_caviar_INDGARCH <- function(coefficients, yes, tau, p, q, maximum, lagged_y, emp_quantil, residuos, VaR_vector, time) {
    .Call(`_QuantileModels_OBJF_unc_caviar_INDGARCH`, coefficients, yes, tau, p, q, maximum, lagged_y, emp_quantil, residuos, VaR_vector, time)
}

unc_caviar_sav <- function(coefficients, p, q, maximum, lagged_y, emp_quantil, VaR_vector, time) {
    .Call(`_QuantileModels_unc_caviar_sav`, coefficients, p, q, maximum, lagged_y, emp_quantil, VaR_vector, time)
}

OBJF_unc_caviar_SAV <- function(coefficients, yes, tau, p, q, maximum, lagged_y, emp_quantil, residuos, VaR_vector, time) {
    .Call(`_QuantileModels_OBJF_unc_caviar_SAV`, coefficients, yes, tau, p, q, maximum, lagged_y, emp_quantil, residuos, VaR_vector, time)
}

unc_caviar_as <- function(coefficients, p, q, maximum, lagged_y, emp_quantil, VaR_vector, time) {
    .Call(`_QuantileModels_unc_caviar_as`, coefficients, p, q, maximum, lagged_y, emp_quantil, VaR_vector, time)
}

OBJF_unc_caviar_AS <- function(coefficients, yes, tau, p, q, maximum, lagged_y, emp_quantil, residuos, VaR_vector, time) {
    .Call(`_QuantileModels_OBJF_unc_caviar_AS`, coefficients, yes, tau, p, q, maximum, lagged_y, emp_quantil, residuos, VaR_vector, time)
}

unc_caviar_i_caviar <- function(coefficients, lagged_abs_y, emp_quantil, positive, VaR_vector, time) {
    .Call(`_QuantileModels_unc_caviar_i_caviar`, coefficients, lagged_abs_y, emp_quantil, positive, VaR_vector, time)
}

OBJF_cons_caviar_ICAV <- function(coefficients, yes, tau, positive, lagged_y, emp_quantil, residuos, VaR_vector, time) {
    .Call(`_QuantileModels_OBJF_cons_caviar_ICAV`, coefficients, yes, tau, positive, lagged_y, emp_quantil, residuos, VaR_vector, time)
}

MVMQ_FILTER <- function(coefficients, lagged_abs_y, N, p, q, VaR_vector, time, maximum) {
    .Call(`_QuantileModels_MVMQ_FILTER`, coefficients, lagged_abs_y, N, p, q, VaR_vector, time, maximum)
}

SAV_FILTER_for_jaco <- function(coefficients, serie, lagged_abs_y, N, p, q, VaR_vector, time, maximum) {
    .Call(`_QuantileModels_SAV_FILTER_for_jaco`, coefficients, serie, lagged_abs_y, N, p, q, VaR_vector, time, maximum)
}

OBJ_F_MVMQ <- function(coefficients, lagged_abs_y, N, p, q, VaR_vector, time, maximum, tau, residuos, series) {
    .Call(`_QuantileModels_OBJ_F_MVMQ`, coefficients, lagged_abs_y, N, p, q, VaR_vector, time, maximum, tau, residuos, series)
}

